import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:your_advising/model/model_login.dart';
import 'package:your_advising/modules/login/cubit/state.dart';
import 'package:your_advising/shared/network/dio_helper.dart';

class LoginCubit extends Cubit<LoginStates> {
  LoginCubit() : super(LoginInitialState());

  static LoginCubit get(context) => BlocProvider.of(context);

  Autogenerated? loginmodel;

  void userLogin({
    required String email,
    required String password,
}){
    emit(LoginLoadingState());
    DioHelper.postdata(
        url: 'all-users-api.php',
        data: {
      'email':email,
      'password':password,
    })
        .then((value)  {
      print(value!.data);
      print(loginmodel?.email);
      emit(LoginSuccessState());
    }).catchError((onError){
      print(onError.toString());
      emit(LoginErrorState(onError.toString()));
    });
  }

  IconData suffix = Icons.visibility_outlined;
  bool ispassword = true;

  void changePasswordVisibility() {
    ispassword = !ispassword;
    suffix = ispassword ? Icons.visibility_off_outlined : Icons.visibility_outlined;
    emit(ChangePasswordState());
  }

}